#!/bin/bash

start=6
stop=13
if [ "$1" != "" ]; then
    stop=$1
fi

rm -rf explicit implicit pruned
touch explicit implicit pruned

echo Timing:
for (( i=$start; i<=$stop; i++ ))
do
    echo $i
    m=$(asy -c "2^$i")
    echo -e "$m \t $(./a.out $m 0 | grep -A 1 Implicit | tail -n 1)"| cat >> implicit
    m=$(asy -c "2^$i")
    echo -e "$m \t $(./a.out $m 1 | grep -A 1 Explicit | tail -n 1)" | cat >> explicit
    m=$(asy -c "2^$i")
    echo -e "$m \t $(./a.out $m 1 | grep -A 1 Pruned | tail -n 1)" | cat >> pruned
done
