#!/bin/bash

for i in conv cconv tconv conv2 cconv2 tconv2 cconv3
do
    
    errorname=""

    if [ "$i" == "conv" ]; then
	outname=timing1r
        errorname=error1r;
    fi
    if [ "$i" == "conv2" ]; then
	outname=timing2r
    fi
    if [ "$i" == "cconv" ]; then
	outname=timing1c
        errorname=error1c;
    fi
    if [ "$i" == "cconv2" ]; then
	outname=timing2c
    fi
    if [ "$i" == "tconv" ]; then
	outname=timing1t
    fi
    if [ "$i" == "tconv2" ]; then
	outname=timing2t
    fi
    if [ "$i" == "cconv3" ]; then
	outname=timing3c
    fi

    asy -v timing -u name=\"$i\" -o ~/dns/tex/$outname
    if [ "$errorname" != "" ]; then
        asy -v error -u name=\"$i\" -o ~/dns/tex/$errorname
    fi

done
