#!/bin/bash

start=6
stop=13

if [ "$1" == "" ]; then
    echo please specify program: timing "["conv\|cconv\|conv2\|cconv2\|biconv\|biconv2"]" "["level"]"
    exit
fi

prune=no

if [ "$1" == "conv" ]; then
    double=no
    outdir=timings1r
fi
if [ "$1" == "conv2" ]; then
    double=no
    outdir=timings2r
    prune=yes
fi
if [ "$1" == "cconv" ]; then
    double=yes
    outdir=timings1c
fi
if [ "$1" == "cconv2" ]; then
    double=yes
    outdir=timings2c
    prune=yes
fi
if [ "$1" == "biconv" ]; then
    double=yes
    outdir=timings1b
fi
if [ "$1" == "biconv2" ]; then
    double=yes
    outdir=timings2b
    prune=yes
fi
if [ "$outdir" == "" ]; then
    echo "wrong program name!"
    exit
fi
mkdir -p $outdir
cd $outdir
rm -rf explicit implicit
touch explicit implicit
cd ..

if [ "$2" != "" ]; then
    stop=$2
fi
echo Timing:
for (( i=$start; i<=$stop; i++ ))
do
    echo $i
    m=$(asy -c "2^$i")
    echo -e "$m \t $(./$1 -x $m -i | grep -A 1 Implicit | tail -n 1)"| cat >> $outdir/implicit
    if [ "$double" == "no" ]; then
	m=$(asy -c "floor((2^($i+1)+2)/3);")
    fi
    echo -e "$m \t $(./$1 -x $m -e | grep -A 1 Explicit | tail -n 1)" | cat >> $outdir/explicit
    if [ "$prune" == "yes" ]; then
	rm -rf $outdir/pruned
	touch $outdir/pruned
	echo -e "$m \t $(./$1 -x $m -p | grep -A 1 Pruned | tail -n 1)" | cat >> $outdir/pruned
    fi

done
